### ISSUE TITLE
Label positioning

### ISSUE THREAD

**Issue by JPWeir** [Graf-Foundation/Graf#16]
Currently, node labels always appear to the right of a node, and can overlap with edges or edge labels. Though this shouldn't affect our functionality much, visually the output would be better for users without overlap.

**Comment by N-Desmarais** [comment]
![depositphotos_107247186-stock-photo-tower-cranes-closeup](https://user-images.githubusercontent.com/55117352/131769777-5a3833cc-d2e9-4cb1-a4d7-6255c84a0ffa.jpg)
