### ISSUE TITLE
Edge weights

### ISSUE THREAD

**Issue by JPWeir** [Graf-Foundation/Graf#65]
Seeing as numerous graph algorithms and topics use edge weights, we should find a way to support edge weights. Likely they could just be paired with our representation of edges.

An extended feature we could also look into support eventually is capacity/flow, as max-flow/min-cut problems are pretty cool.

**Comment by semicolon-madness** [comment]
Hey - I think this is closed.  Edge weights have been implemented, as well as the max flow algorithm from my team.  I'm going to look into merging the (all properly working now) new algorithms into your website when I get the chance.

**Comment by N-Desmarais** [comment]
![depositphotos_107247186-stock-photo-tower-cranes-closeup](https://user-images.githubusercontent.com/55117352/131770112-d261fe5c-c523-4e05-9932-54bdc3cebd6a.jpg)
