### ISSUE TITLE
Export to Latex

### ISSUE THREAD

**Issue by Prasantacharya** [Graf-Foundation/Graf#90]
I think it would be nice if the graphs created could be rendered/exported to latex. I find myself working with graphs mostly in latex papers, so it would be very helpful if I could just build them in Graf, and copy+paste into the latex doc.

**Comment by N-Desmarais** [comment]
Is there a specific file format you're looking for? 

You can always take a screenshot and include the image in latex, or use the export to svg feature.

**Comment by Prasantacharya** [comment]
> Is there a specific file format you're looking for?
> 
> You can always take a screenshot and include the image in latex, or use the export to svg feature.

It would probably be `.tex`. 
For the screenshot, using external pictures in latex is surprisingly annoying because it rarely centers the way you want it even with fiddling with it. SVG's are similar. So exporting it to tex is just more convenient.

**Comment by johnnyapol** [comment]
Export to LaTeX via tikz would probably make the most sense IMO. Similar to how it works on MadeByEvan's FSM generator http://madebyevan.com/fsm/

**Comment by N-Desmarais** [comment]
![depositphotos_107247186-stock-photo-tower-cranes-closeup](https://user-images.githubusercontent.com/55117352/131769958-e9ba3561-35dd-482d-a246-d5dc8b1d3890.jpg)
